---
baseURL: "https://marquettelearningcenter.com/"
languageCode: "en-us"
title: "Marquette Learning Center"
disableKinds: ["RSS","taxonomyTerm"]
params:
  facebookURL: "https://www.facebook.com/marquettelearningcenter"
...
