backend:
  name: git-gateway
  branch: master

site_url: https://marquettelearningcenter.netlify.com

editor:
  preview: false

logo_url: https://marquettelearningcenter.netlify.com/img/icons/marquette-learning-center-144.png

media_folder: "static/img/uploads" # Folder where user uploaded files should go
public_folder: "/img/uploads" # The src attribute for uploaded files

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: Vacancies
            name: vacancies
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: string
