backend:
  name: git-gateway
  branch: master

site_url: https://marquettelearningcenter.com
display_url: https://marquettelearningcenter.com
logo_url: https://marquettelearningcenter.com/img/icons/marquette-learning-center-144.png

editor:
  preview: false

media_folder: "static/img/uploads" # Folder where user uploaded files should go
public_folder: "/img/uploads" # The src attribute for uploaded files

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: Vacancies
            name: vacancies
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: string
      - file: "content/hours-tuition/_index.md"
        label: "Hours & Tuition"
        name: "hours_tuition"
        fields:
          - label: Hours Open
            name: hours_open
            widget: string
          - label: Hours Closed
            name: hours_closed
            widget: string
  - name: "global"
    label: "Global"
    files:
      - file: "data/alert.yaml"
        label: "Alert"
        name: "alert"
        fields:
          - {label: Active, name: active, widget: boolean, default: false}
          - {label: Message, name: message, widget: markdown, buttons: [bold, italic, link]}
          - {label: Additional Information, name: additional_information, required: false, widget: markdown, buttons: [bold, italic, link]}
