backend:
  name: git-gateway
  branch: master

media_folder: "static/img/uploads" # Folder where user uploaded files should go
public_folder: "/img/uploads" # The src attribute for uploaded files

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Room1Vacancies", name: room1vacancies, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Room2Vacancies", name: room2vacancies, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
